# Generated by Django 5.1.5 on 2025-03-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QG', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizScore',
        ),
    ]
