# Generated by Django 5.1.5 on 2025-06-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QG', '0003_quiz_useranswer_quizresult_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
