# Generated by Django 5.1.5 on 2025-06-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QG', '0004_mcqquestion_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='session',
            field=models.CharField(default='Unknown Course', max_length=50),
        ),
    ]
