# Generated by Django 5.1.5 on 2025-06-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QG', '0005_alter_quizresult_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
