# Generated by Django 5.1.5 on 2025-06-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QG', '0006_delete_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(null=True)),
                ('quiz', models.IntegerField(null=True)),
                ('session', models.CharField(default='Unknown Course', max_length=50)),
                ('course', models.IntegerField(null=True)),
                ('score', models.FloatField()),
            ],
            options={
                'unique_together': {('user', 'quiz', 'session')},
            },
        ),
    ]
