# Generated by Django 5.1.5 on 2025-02-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='csknowledge',
            name='trackid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
