# Generated by Django 5.1.5 on 2025-02-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_csknowledge_trackid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disability_type',
            field=models.CharField(choices=[('visual', 'Visual Impairment'), ('hearing', 'Hearing Impairment'), ('physical', 'Physical Impairment'), ('cognitive', 'Cognitive Impairment'), ('none', 'No Disability')], default='none', max_length=20),
        ),
    ]
