# Generated by Django 5.1.5 on 2025-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('Quiz', 'Take this quiz to determine your level!')], default='beginner', max_length=50),
        ),
    ]
