# Generated by Django 5.1.5 on 2025-02-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='disability_type',
            field=models.CharField(choices=[('visual', 'Visual Impairment'), ('auditory', 'Auditory Impairment'), ('physical', 'Physical Impairment'), ('cognitive', 'Cognitive Impairment'), ('none', 'No Disability')], default='none', max_length=20),
        ),
    ]
