# Generated by Django 5.1.5 on 2025-06-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0003_userroadmaps_user_ques_answers_user_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroadmaps',
            name='course',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
