# Generated by Django 5.1.5 on 2025-06-16 13:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_alter_userroadmaps_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroadmaps',
            name='roadmap_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
