# Generated by Django 5.1.5 on 2025-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0005_userroadmaps_roadmap_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_ques_answers',
            name='user_roadmap',
        ),
        migrations.AddField(
            model_name='user_ques_answers',
            name='roadmap_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
