# Generated by Django 5.1.5 on 2025-06-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_remove_user_ques_answers_user_roadmap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroadmaps',
            name='course_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
