# Generated by Django 5.1.5 on 2025-02-16 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerid', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField(db_column='answer')),
                ('is_correct', models.BooleanField(db_column='iscorrect', default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True, db_column='answeredat')),
                ('question', models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'useranswers',
            },
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
