# Generated by Django 5.1.5 on 2025-02-19 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_remove_answer_answered_at_remove_answer_is_correct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answeredat',
            field=models.DateTimeField(auto_now_add=True, db_column='answeredat'),
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answeredat',
            new_name='answered_at',
        ),
        migrations.AlterField(
            model_name='answer',
            name='iscorrect',
            field=models.BooleanField(db_column='iscorrect', default=False),
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='iscorrect',
            new_name='is_correct',
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(db_column='answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
