# Generated by Django 5.1.5 on 2025-02-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_remove_courses_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='track_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='courses.tracks'),
        ),
    ]
