# Generated by Django 5.1.5 on 2025-02-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_playlist_track_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='track_id',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tracks',
            name='id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='courses.tracks'),
        ),
        migrations.AddField(
            model_name='tracks',
            name='track_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
