# Generated by Django 5.1.5 on 2025-06-13 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_remove_playlist_track_id_remove_tracks_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='rating',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='level',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='quiz_score',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='userid',
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='sessionsnumber',
            field=models.IntegerField(blank=True, default=0, help_text='Number of sessions in this course', null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='sessionOrder',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
