# Generated by Django 5.1.5 on 2025-06-16 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_rename_rating_courses_rate_remove_courses_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='track',
            field=models.ForeignKey(blank=True, db_column='track_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.tracks'),
        ),
    ]
