# Generated by Django 5.1.5 on 2025-06-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_playlist_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='trackid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='track',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Tracks',
        ),
    ]
